name: Check Linter

on: 
  - push
  - pull_request

jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with: 
           node-version: "16"
       - name: npm install
         run: make install
       - name: run lint
         run: make lint

