name: Node.js CI

on: 
  - push
  - pull_request

jobs:
   lint:
     run-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [14.x]
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v1
         with: 
           node-version: ${{ matrix.node-version }}
       - name: npm install
         run: make install
       - name: run lint
         run: make lint

